//! Vendored UNIMOD chemistry, embedded at compile time and parsed once on first use.
//!
//! `data/elements.tsv` and `data/unimod.tsv` are generated by `tools/gen_unimod.py` — see that
//! script for the source URL and terms. Nothing here is hand-maintained; regenerate rather
//! than edit.
//!
//! Both TSVs open with a `#`-prefixed provenance/license header (UNIMOD copyright, the Design
//! Science License, and a description of the transformation applied) so the notice ships with
//! the redistributed artifact itself — not just the generator's docstring. `tables()` below
//! skips those lines rather than parsing them as data.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::composition::AtomicComposition;

const ELEMENTS_TSV: &str = include_str!("../data/elements.tsv");
const UNIMOD_TSV: &str = include_str!("../data/unimod.tsv");

/// Our historical modification names -> UNIMOD accession.
///
/// These four are a frozen contract on the **read** side: serialized precursor caches and
/// prepared `mods` columns in the wild use them, so `by_name` must keep accepting them forever.
/// They are deliberately *not* a vocabulary we emit. Two of them (`Carbamidomethyl@C`,
/// `Oxidation@M`) carry alphabase-style `@Site` suffixes that are not valid ProForma descriptors,
/// so emitting them yields modified sequences our own grammar cannot parse — see
/// `ModSpec::render`, which resolves every named modification to its accession instead.
pub const ALIASES: &[(&str, u32)] = &[
    ("Carbamidomethyl@C", 4),
    ("Phospho", 21),
    ("Oxidation@M", 35),
    ("TMT6plex", 737),
];

#[derive(Debug, Clone)]
pub struct ModEntry {
    pub accession: u32,
    pub title: String,
    pub comp: AtomicComposition,
    /// Vendored from UNIMOD. Used only to cross-check the computed mass — never read as the
    /// authoritative delta, which always comes from `comp`.
    pub mono_mass: f64,
}

struct Tables {
    masses: HashMap<String, f64>,
    entries: Vec<ModEntry>,
    by_acc: HashMap<u32, usize>,
    by_title: HashMap<String, usize>,
}

static TABLES: OnceLock<Tables> = OnceLock::new();

fn tables() -> &'static Tables {
    TABLES.get_or_init(|| {
        let mut masses = HashMap::new();
        for (lineno, line) in ELEMENTS_TSV.lines().enumerate() {
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let (sym, mass) = line
                .split_once('\t')
                .unwrap_or_else(|| panic!("elements.tsv:{} malformed: {line:?}", lineno + 1));
            let mass: f64 = mass
                .parse()
                .unwrap_or_else(|_| panic!("elements.tsv:{} bad mass: {line:?}", lineno + 1));
            masses.insert(sym.to_string(), mass);
        }

        let mut entries = Vec::new();
        for (lineno, line) in UNIMOD_TSV.lines().enumerate() {
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let f: Vec<&str> = line.split('\t').collect();
            assert_eq!(f.len(), 4, "unimod.tsv:{} malformed: {line:?}", lineno + 1);
            entries.push(ModEntry {
                accession: f[0].parse().expect("unimod.tsv: bad accession"),
                title: f[1].to_string(),
                comp: AtomicComposition::parse(f[2]).expect("unimod.tsv: bad composition"),
                mono_mass: f[3].parse().expect("unimod.tsv: bad mono_mass"),
            });
        }

        let by_acc = entries
            .iter()
            .enumerate()
            .map(|(i, e)| (e.accession, i))
            .collect();
        let by_title = entries
            .iter()
            .enumerate()
            .map(|(i, e)| (e.title.clone(), i))
            .collect();
        Tables {
            masses,
            entries,
            by_acc,
            by_title,
        }
    })
}

pub fn nuclide_masses() -> &'static HashMap<String, f64> {
    &tables().masses
}

pub fn all_entries() -> &'static [ModEntry] {
    &tables().entries
}

pub fn by_accession(acc: u32) -> Option<&'static ModEntry> {
    let t = tables();
    t.by_acc.get(&acc).map(|i| &t.entries[*i])
}

/// Resolve a canonical name: our alias if one exists, otherwise a UNIMOD title.
pub fn by_name(name: &str) -> Option<&'static ModEntry> {
    if let Some((_, acc)) = ALIASES.iter().find(|(n, _)| *n == name) {
        return by_accession(*acc);
    }
    let t = tables();
    t.by_title.get(name).map(|i| &t.entries[*i])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_load_and_are_nonempty() {
        assert!(nuclide_masses().len() > 10);
        assert!(all_entries().len() > 500);
    }

    #[test]
    fn every_entry_mass_matches_its_composition() {
        // The whole point of vendoring mono_mass: one assertion covers every row, so a bad
        // element mass or parser bug cannot hide in a modification nobody uses yet. A row
        // whose nuclide is missing from elements.tsv is a build-integrity failure exactly like
        // a malformed row, so it must fail this test rather than be skipped by it.
        let masses = nuclide_masses();
        for e in all_entries() {
            let computed = e
                .comp
                .mono_mass(masses)
                .unwrap_or_else(|err| panic!("accession {} ({}): {err}", e.accession, e.title));
            assert!(
                (computed - e.mono_mass).abs() < 1e-5,
                "accession {} ({}): computed {} vs vendored {}",
                e.accession,
                e.title,
                computed,
                e.mono_mass
            );
        }
    }

    #[test]
    fn header_lines_are_skipped_not_parsed_as_data() {
        // tools/gen_unimod.py prefixes both TSVs with '#'-prefixed provenance/license comment
        // lines so the UNIMOD notice ships with the data itself. Those lines have no real tab
        // characters (the header text uses literal backslash-t, not tabs), so if the loader
        // ever stopped skipping them they would blow up as "malformed" rows in `tables()` —
        // this test locks the header format itself, independent of that panic.
        assert!(ELEMENTS_TSV.lines().next().unwrap().starts_with('#'));
        assert!(UNIMOD_TSV.lines().next().unwrap().starts_with('#'));

        let elements_data_lines = ELEMENTS_TSV
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .count();
        let unimod_data_lines = UNIMOD_TSV
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .count();
        assert_eq!(nuclide_masses().len(), elements_data_lines);
        assert_eq!(all_entries().len(), unimod_data_lines);
    }

    #[test]
    fn known_accessions_resolve() {
        assert_eq!(by_accession(21).unwrap().title, "Phospho");
        assert_eq!(by_accession(737).unwrap().title, "TMT6plex");
        assert!(by_accession(99_999_999).is_none());
    }

    #[test]
    fn aliases_resolve_to_the_same_entry() {
        assert_eq!(by_name("Carbamidomethyl@C").unwrap().accession, 4);
        assert_eq!(by_name("Oxidation@M").unwrap().accession, 35);
        // A bare UNIMOD title works too, for mods with no alias.
        assert_eq!(by_name("Phospho").unwrap().accession, 21);
        assert!(by_name("NotAMod").is_none());
    }

    #[test]
    fn tmt6plex_element_comp_diverges_from_its_mass() {
        let e = by_accession(737).unwrap();
        assert_eq!(e.comp.element_comp().unwrap(), [12, 20, 2, 2, 0, 0]);
        // The element view's "natural" mass is ~5 Da lighter than the real delta. Both
        // channels are kept precisely because of this.
        assert!((e.mono_mass - 229.162_932_1).abs() < 1e-5);
    }
}
